version: '3.4'

services:
  minimal-api:
    image: ${DOCKER_REGISTRY-}minimal-api
    container_name: Minimal.Api
    build:
      context: .
      dockerfile: Minimal.Api/Dockerfile
    ports:
      - "5001:443"

  minimal-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Minimal.Db
    volumes:
        - ./.containers/database:/var/opt/mssql/data
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Strong_password_123!"
